/** Application-wide limits and defaults */
export const LIMITS = {
  /** Search */
  SEARCH_RADIUS_DEFAULT_MILES: 25,
  SEARCH_RADIUS_MAX_MILES: 100,
  SEARCH_PAGE_SIZE_DEFAULT: 20,
  SEARCH_PAGE_SIZE_MAX: 100,

  /** Listings */
  LISTING_TITLE_MAX_LENGTH: 200,
  LISTING_DESCRIPTION_MAX_LENGTH: 5000,
  LISTING_MAX_MEDIA: 20,
  LISTING_EXPIRY_DAYS: 30,
  LISTING_DAILY_POST_LIMIT_DEFAULT: 5,
  LISTING_DAILY_POST_LIMIT_VERIFIED: 20,

  /** Media */
  IMAGE_MAX_SIZE_BYTES: 10 * 1024 * 1024, // 10 MB
  VIDEO_MAX_SIZE_BYTES: 100 * 1024 * 1024, // 100 MB
  IMAGE_MAX_DIMENSION_PX: 4096,
  IMAGE_PROCESSED_SIZES: [150, 400, 800] as const,

  /** Messages */
  MESSAGE_MAX_LENGTH: 2000,
  MESSAGE_RATE_LIMIT_PER_MINUTE: 60,

  /** Promotions */
  PROMOTION_MIN_DURATION_DAYS: 1,
  PROMOTION_MAX_DURATION_DAYS: 30,

  /** Saved searches */
  SAVED_SEARCHES_MAX: 25,

  /** Auth */
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  DISPLAY_NAME_MIN_LENGTH: 2,
  DISPLAY_NAME_MAX_LENGTH: 50,
  OTP_LENGTH: 6,
  OTP_COOLDOWN_SECONDS: 60,
  MAX_SESSIONS_PER_USER: 10,

  /** Moderation */
  RISK_SCORE_AUTO_APPROVE_MAX: 30,
  RISK_SCORE_HOLD_FOR_REVIEW_MIN: 61,
} as const;

/** Miles to meters conversion factor */
export const MILES_TO_METERS = 1609.344;
